"""Gazetteer of Harvard / Cambridge event venues.

Event listings rarely give coordinates; they give things like "WCC 3019",
"L-166", or "Knafel Center, Radcliffe Yard". Each entry below maps such
strings to one building.

Entry format:
    (key, display name, [geocoding queries, best first], [alias regexes])

An alias may be a tuple (regex, {source ids}) to restrict it to certain
sources -- e.g. HKS room codes like "L-166" only mean Littauer when the
event comes from the HKS calendar.

ORDER MATTERS: the first entry with a matching alias wins, so specific
buildings come before whole campuses ("Belfer Case Study Room, CGIS South"
must hit CGIS South before the HKS Belfer Building).

Coordinates are resolved once with tools/build_places.py (OpenStreetMap
Nominatim) and stored in data/places.json; this file is the source of truth
for names and aliases.
"""

HKS_ONLY = {"hks"}

PLACES = [
    # --- Nieman home base -------------------------------------------------
    ("lippmann", "Lippmann House (Nieman Foundation)",
     ["Lippmann House, Cambridge, MA", "1 Francis Avenue, Cambridge, MA 02138"],
     [r"lippmann house", r"nieman foundation", r"\b1 francis ave"]),

    # --- Radcliffe (before CGIS: "Knafel Center" is Radcliffe) ------------
    ("radcliffe_knafel", "Knafel Center, Radcliffe Yard",
     ["Knafel Center, Cambridge, MA", "10 Garden Street, Cambridge, MA 02138"],
     [r"knafel center", r"radcliffe (?:institute|yard|gymnasium)", r"10 garden st"]),
    ("byerly", "Byerly Hall, Radcliffe Yard",
     ["Byerly Hall, Cambridge, MA", "8 Garden Street, Cambridge, MA 02138"],
     [r"byerly"]),
    ("schlesinger", "Schlesinger Library, Radcliffe Yard",
     ["Schlesinger Library, Cambridge, MA", "3 James Street, Cambridge, MA 02138"],
     [r"schlesinger", r"agassiz house", r"fay house"]),

    # --- CGIS & FAS area centers -------------------------------------------
    ("cgis_south", "CGIS South Building",
     ["CGIS South Building, Cambridge, MA", "1730 Cambridge Street, Cambridge, MA 02138"],
     [r"cgis[ -]?s(?:outh)?\b", r"tsai auditorium", r"belfer case study", r"1730 cambridge",
      r"fairbank center", r"davis center", r"david rockefeller center", r"\bdrclas\b",
      r"center for middle eastern studies", r"asia center", r"reischauer",
      r"korea institute", r"south asia institute", r"lakshmi mittal"]),
    ("cgis_knafel", "CGIS Knafel Building",
     ["CGIS Knafel Building, Cambridge, MA", "1737 Cambridge Street, Cambridge, MA 02138"],
     [r"cgis[ -]?k(?:nafel)?\b", r"knafel (?:building|bldg)", r"\bcgis\b", r"1737 cambridge",
      r"weatherhead", r"\bwcfia\b", r"center for government and international studies"]),
    ("busch", "Adolphus Busch Hall (Center for European Studies)",
     ["Adolphus Busch Hall, Cambridge, MA", "27 Kirkland Street, Cambridge, MA 02138"],
     [r"adolphus busch", r"busch hall", r"center for european studies", r"27 kirkland"]),
    ("william_james", "William James Hall",
     ["William James Hall, Cambridge, MA", "33 Kirkland Street, Cambridge, MA 02138"],
     [r"william james", r"\bwjh\b", r"33 kirkland"]),
    ("huri", "Harvard Ukrainian Research Institute",
     ["34 Kirkland Street, Cambridge, MA 02138"],
     [r"ukrainian research", r"\bhuri\b", r"34 kirkland"]),
    ("lowell_lecture", "Lowell Lecture Hall",
     ["Lowell Lecture Hall, Cambridge, MA", "17 Kirkland Street, Cambridge, MA 02138"],
     [r"lowell lecture"]),
    ("barker", "Barker Center",
     ["Barker Center, Cambridge, MA", "12 Quincy Street, Cambridge, MA 02138"],
     [r"barker center", r"thompson room", r"mahindra", r"12 quincy"]),

    # --- Harvard Yard & Quincy Street ----------------------------------------
    ("smith_center", "Smith Campus Center",
     ["Smith Campus Center, Cambridge, MA", "1350 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"smith (?:campus )?center", r"harvard commons", r"1350 mass"]),
    ("science_center", "Science Center",
     ["Harvard Science Center, Cambridge, MA", "1 Oxford Street, Cambridge, MA 02138"],
     [r"science center", r"cabot science library", r"\b1 oxford st"]),
    ("sever", "Sever Hall", ["Sever Hall, Cambridge, MA"], [r"sever hall", r"\bsever \d"]),
    ("emerson", "Emerson Hall", ["Emerson Hall, Cambridge, MA"], [r"emerson hall", r"\bemerson \d"]),
    ("robinson", "Robinson Hall", ["Robinson Hall, Cambridge, MA"], [r"robinson hall", r"warren center"]),
    ("boylston", "Boylston Hall", ["Boylston Hall, Cambridge, MA"], [r"boylston hall", r"fong auditorium", r"ticknor lounge"]),
    ("harvard_hall", "Harvard Hall", ["Harvard Hall, Harvard Yard, Cambridge, MA"], [r"harvard hall \d", r"^harvard hall"]),
    ("university_hall", "University Hall", ["University Hall, Harvard Yard, Cambridge, MA"], [r"university hall"]),
    ("widener", "Widener Library", ["Widener Library, Cambridge, MA"], [r"widener"]),
    ("lamont", "Lamont Library", ["Lamont Library, Cambridge, MA"], [r"lamont"]),
    ("houghton", "Houghton Library", ["Houghton Library, Cambridge, MA"], [r"houghton"]),
    ("memorial_church", "Memorial Church", ["Memorial Church, Harvard Yard, Cambridge, MA"],
     [r"memorial church", r"sparks house", r"appleton chapel"]),
    ("memorial_hall", "Memorial Hall / Sanders Theatre",
     ["Memorial Hall, Cambridge, MA", "45 Quincy Street, Cambridge, MA 02138"],
     [r"memorial hall", r"sanders theat", r"annenberg hall", r"45 quincy"]),
    ("art_museums", "Harvard Art Museums",
     ["Harvard Art Museums, Cambridge, MA", "32 Quincy Street, Cambridge, MA 02138"],
     [r"harvard art museums?", r"menschel hall", r"fogg", r"32 quincy"]),
    ("carpenter", "Carpenter Center",
     ["Carpenter Center for the Visual Arts, Cambridge, MA", "24 Quincy Street, Cambridge, MA 02138"],
     [r"carpenter center", r"harvard film archive", r"24 quincy"]),
    ("faculty_club", "Harvard Faculty Club",
     ["Harvard Faculty Club, Cambridge, MA", "20 Quincy Street, Cambridge, MA 02138"],
     [r"faculty club", r"20 quincy"]),
    ("loeb_house", "Loeb House", ["17 Quincy Street, Cambridge, MA 02138"], [r"loeb house", r"17 quincy"]),
    ("gund", "Gund Hall (Graduate School of Design)",
     ["Gund Hall, Cambridge, MA", "48 Quincy Street, Cambridge, MA 02138"],
     [r"gund hall", r"piper auditorium", r"stubbins", r"graduate school of design", r"\bgsd\b", r"48 quincy"]),
    ("music_building", "Music Building / Paine Hall",
     ["Paine Hall, Cambridge, MA", "3 Oxford Street, Cambridge, MA 02138"],
     [r"paine hall", r"music building", r"davison room"]),

    # --- Oxford St / Divinity Ave / Francis Ave --------------------------------
    ("hmnh", "Harvard Museum of Natural History",
     ["Harvard Museum of Natural History, Cambridge, MA", "26 Oxford Street, Cambridge, MA 02138"],
     [r"museum of natural history", r"\bhmnh\b", r"geological (?:lecture|museum)", r"haller hall",
      r"24 oxford", r"26 oxford"]),
    ("pierce", "Pierce Hall / Maxwell Dworkin (SEAS)",
     ["Pierce Hall, Cambridge, MA", "29 Oxford Street, Cambridge, MA 02138"],
     [r"pierce hall", r"\bpierce [g\d]\d", r"maxwell dworkin", r"29 oxford", r"33 oxford"]),
    ("northwest", "Northwest Building", ["Northwest Building, Cambridge, MA", "52 Oxford Street, Cambridge, MA 02138"],
     [r"northwest (?:building|lab)", r"\bnwb\b", r"52 oxford"]),
    ("mallinckrodt", "Mallinckrodt Laboratory", ["Mallinckrodt Laboratory, Cambridge, MA", "12 Oxford Street, Cambridge, MA 02138"],
     [r"mallinckrodt", r"12 oxford"]),
    ("peabody", "Peabody Museum",
     ["Peabody Museum of Archaeology and Ethnology, Cambridge, MA", "11 Divinity Avenue, Cambridge, MA 02138"],
     [r"peabody museum", r"11 divinity", r"tozzer"]),
    ("semitic", "Harvard Museum of the Ancient Near East",
     ["6 Divinity Avenue, Cambridge, MA 02138"],
     [r"ancient near east", r"semitic museum", r"6 divinity"]),
    ("yenching", "Harvard-Yenching Institute",
     ["Harvard-Yenching Institute, Cambridge, MA", "2 Divinity Avenue, Cambridge, MA 02138"],
     [r"yenching", r"2 divinity"]),
    ("biolabs", "Biological Laboratories", ["Biological Laboratories, Cambridge, MA", "16 Divinity Avenue, Cambridge, MA 02138"],
     [r"biological lab", r"biolabs", r"16 divinity"]),
    ("hds", "Harvard Divinity School (Andover Hall)",
     ["Andover Hall, Cambridge, MA", "45 Francis Avenue, Cambridge, MA 02138"],
     [r"andover hall", r"swartz hall", r"sperry room", r"rockefeller hall", r"divinity school", r"\bhds\b",
      r"45 francis"]),
    ("cswr", "Center for the Study of World Religions",
     ["42 Francis Avenue, Cambridge, MA 02138"],
     [r"study of world religions", r"\bcswr\b", r"42 francis"]),

    # --- Harvard Law School ------------------------------------------------------
    ("hls_wcc", "Wasserstein Hall (WCC), Harvard Law School",
     ["Wasserstein Hall, Cambridge, MA", "1585 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"\bwcc\b", r"wasserstein", r"caspersen", r"milstein", r"1585 mass"]),
    ("hls_austin", "Austin Hall, Harvard Law School",
     ["Austin Hall, Cambridge, MA", "1515 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"austin hall", r"\baustin (?:east|west|north|\d)", r"ames courtroom", r"1515 mass"]),
    ("hls_langdell", "Langdell Hall, Harvard Law School",
     ["Langdell Hall, Cambridge, MA", "1545 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"langdell", r"1545 mass"]),
    ("hls_hauser", "Hauser Hall, Harvard Law School",
     ["Hauser Hall, Cambridge, MA", "1575 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"hauser", r"1575 mass"]),
    ("hls_pound", "Pound Hall, Harvard Law School",
     ["Pound Hall, Cambridge, MA", "1563 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"pound hall", r"\bpound \d", r"1563 mass"]),
    ("hls_griswold", "Griswold Hall, Harvard Law School",
     ["Griswold Hall, Cambridge, MA", "1525 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"griswold", r"1525 mass"]),
    ("hls_lewis", "Lewis International Law Center, HLS",
     ["Lewis International Law Center, Cambridge, MA", "1557 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"lewis (?:international|center|\d)"]),
    ("hls_areeda", "Areeda Hall, Harvard Law School", ["Areeda Hall, Cambridge, MA"], [r"areeda"]),
    ("hls_hark", "Harkness Commons, Harvard Law School",
     ["Harkness Commons, Cambridge, MA", "1557 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"harkness", r"\bhark\b"]),
    ("hls", "Harvard Law School",
     ["Harvard Law School, Cambridge, MA", "1563 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"harvard law school", r"\bhls\b"]),

    # --- Graduate School of Education -------------------------------------------
    ("gse", "Graduate School of Education (Appian Way)",
     ["Gutman Library, Cambridge, MA", "6 Appian Way, Cambridge, MA 02138"],
     [r"gutman", r"longfellow hall", r"larsen hall", r"askwith", r"appian way", r"graduate school of education", r"\bhgse\b"]),

    # --- Mount Auburn St & Harvard Square ---------------------------------------
    ("ash", "Ash Center (124 Mt Auburn St)",
     ["124 Mount Auburn Street, Cambridge, MA 02138"],
     [r"124 (?:mount|mt\.?) auburn", r"ash center"]),
    ("hutchins", "Hutchins Center for African & African American Research",
     ["104 Mount Auburn Street, Cambridge, MA 02138"],
     [r"hutchins center", r"cooper gallery", r"104 (?:mount|mt\.?) auburn", r"102 (?:mount|mt\.?) auburn"]),
    ("hillel", "Harvard Hillel (Rosovsky Hall)",
     ["52 Mount Auburn Street, Cambridge, MA 02138"],
     [r"hillel", r"rosovsky", r"52 (?:mount|mt\.?) auburn"]),
    ("berkman", "Berkman Klein Center",
     ["23 Everett Street, Cambridge, MA 02138"],
     [r"berkman", r"23 everett"]),
    ("farkas", "Farkas Hall", ["Farkas Hall, Cambridge, MA", "12 Holyoke Street, Cambridge, MA 02138"],
     [r"farkas hall", r"12 holyoke"]),
    ("loeb_drama", "Loeb Drama Center (A.R.T.)",
     ["Loeb Drama Center, Cambridge, MA", "64 Brattle Street, Cambridge, MA 02138"],
     [r"loeb drama", r"american repertory theater", r"64 brattle"]),
    ("arts29", "Arts @ 29 Garden", ["29 Garden Street, Cambridge, MA 02138"], [r"29 garden"]),
    ("cfa", "Center for Astrophysics", ["60 Garden Street, Cambridge, MA 02138"],
     [r"center for astrophysics", r"phillips auditorium", r"60 garden"]),
    ("book_store", "Harvard Book Store", ["Harvard Book Store, Cambridge, MA", "1256 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"harvard book store", r"1256 mass"]),
    ("first_parish", "First Parish in Cambridge", ["1446 Massachusetts Avenue, Cambridge, MA 02138"],
     [r"first parish", r"1446 mass"]),
    ("phillips_brooks", "Phillips Brooks House", ["Phillips Brooks House, Cambridge, MA"], [r"phillips brooks"]),
    ("lehman", "Lehman Hall / Dudley House", ["Lehman Hall, Cambridge, MA"], [r"lehman hall", r"dudley house"]),

    # --- Undergraduate Houses ---------------------------------------------------
    ("adams", "Adams House", ["Adams House, Cambridge, MA"], [r"adams house"]),
    ("lowell", "Lowell House", ["Lowell House, Cambridge, MA"], [r"lowell house"]),
    ("quincy", "Quincy House", ["Quincy House, Cambridge, MA"], [r"quincy house"]),
    ("leverett", "Leverett House", ["Leverett House, Cambridge, MA"], [r"leverett"]),
    ("winthrop", "Winthrop House", ["Winthrop House, Cambridge, MA"], [r"winthrop house"]),
    ("eliot", "Eliot House", ["Eliot House, Cambridge, MA"], [r"eliot house"]),
    ("kirkland", "Kirkland House", ["Kirkland House, Cambridge, MA"], [r"kirkland house"]),
    ("dunster", "Dunster House", ["Dunster House, Cambridge, MA"], [r"dunster house"]),
    ("mather", "Mather House", ["Mather House, Cambridge, MA"], [r"mather house"]),
    ("cabot", "Cabot House", ["Cabot House, Cambridge, MA"], [r"cabot house"]),
    ("currier", "Currier House", ["Currier House, Cambridge, MA"], [r"currier house"]),
    ("pfoho", "Pforzheimer House", ["Pforzheimer House, Cambridge, MA"], [r"pforzheimer", r"pfoho"]),

    # --- Harvard Kennedy School (after CGIS so "Belfer Case Study Room" is not HKS) ---
    ("hks_littauer", "Littauer Building, Harvard Kennedy School",
     ["Littauer Center of Public Administration, Cambridge, MA", "Littauer Center, Cambridge, MA"],
     [r"littauer", r"jfk jr\.? forum", r"forum,? (?:littauer|hks)", r"malkin penthouse", r"fainsod",
      r"institute of politics", (r"^\s*l-?\d{2,3}", HKS_ONLY)]),
    ("hks_taubman", "Taubman Building, Harvard Kennedy School",
     ["Taubman Building, Cambridge, MA", "15 Eliot Street, Cambridge, MA 02138"],
     [r"taubman", r"\bnye [abc]\b", r"nye conference", r"allison dining", r"wiener auditorium",
      r"shorenstein", (r"^\s*t-?\d{2,3}", HKS_ONLY)]),
    ("hks_belfer", "Belfer Building, Harvard Kennedy School",
     ["Belfer Building, Cambridge, MA", "Belfer Center for Science and International Affairs, Cambridge, MA"],
     [r"belfer (?:building|bldg|\d|5th)", r"bell hall", r"weil town hall", r"starr auditorium",
      (r"^\s*b-?\d{2,3}", HKS_ONLY)]),
    ("hks_rubenstein", "Rubenstein Building, Harvard Kennedy School",
     ["Rubenstein Building, Cambridge, MA", "Harvard Kennedy School Rubenstein Building"],
     [r"rubenstein (?:building|bldg|\d)", (r"^\s*r-?\d{2,3}", HKS_ONLY), (r"rubenstein", HKS_ONLY)]),
    ("hks_wexner", "Wexner Building, Harvard Kennedy School",
     ["Wexner Building, Cambridge, MA"],
     [r"wexner", (r"^\s*w-?\d{2,3}", HKS_ONLY)]),
    ("hks", "Harvard Kennedy School",
     ["Harvard Kennedy School, Cambridge, MA", "79 John F. Kennedy Street, Cambridge, MA 02138"],
     [r"kennedy school", r"\bhks\b", r"79 (?:john f\.? kennedy|jfk)"]),

    # --- Allston ------------------------------------------------------------------
    ("seas_sec", "Science & Engineering Complex (Allston)",
     ["Harvard Science and Engineering Complex, Boston, MA", "150 Western Avenue, Boston, MA 02134"],
     [r"science (?:and|&) engineering complex", r"\bsec\b", r"150 western"]),
    ("treehouse", "David Rubenstein Treehouse (Allston)",
     ["David Rubenstein Treehouse, Boston, MA", "100 Western Avenue, Boston, MA 02134"],
     [r"treehouse"]),
    ("ilab", "Harvard Innovation Labs (Allston)",
     ["Harvard Innovation Labs, Boston, MA", "125 Western Avenue, Boston, MA 02134"],
     [r"innovation labs?", r"\bi-?lab\b", r"pagliuca", r"125 western"]),
    ("ed_portal", "Harvard Ed Portal (Allston)",
     ["224 Western Avenue, Boston, MA 02134"],
     [r"ed portal", r"224 western"]),
    ("hbs", "Harvard Business School",
     ["Harvard Business School, Boston, MA", "Soldiers Field Road, Boston, MA 02163"],
     [r"harvard business school", r"\bhbs\b", r"spangler", r"klarman hall", r"aldrich hall", r"hawes hall",
      r"soldiers field"]),

    # --- Longwood -------------------------------------------------------------------
    ("hsph", "Harvard Chan School of Public Health (Longwood)",
     ["Harvard T.H. Chan School of Public Health, Boston, MA", "677 Huntington Avenue, Boston, MA 02115"],
     [r"chan school", r"\bhsph\b", r"kresge", r"\bfxb\b", r"677 huntington", r"school of public health"]),
    ("hms", "Harvard Medical School (Longwood)",
     ["Harvard Medical School, Boston, MA", "25 Shattuck Street, Boston, MA 02115"],
     [r"harvard medical school", r"\bhms\b", r"\btmec\b", r"gordon hall", r"countway", r"25 shattuck"]),

    # --- Catch-alls -------------------------------------------------------------------
    ("harvard_yard", "Harvard Yard", ["Harvard Yard, Cambridge, MA"], [r"harvard yard", r"tercentenary theatre"]),
]
